#!/bin/bash
###############################################################################
# iccDEV issue 1097 iccApplyProfiles CAM sub-element HBO regression test
###############################################################################
#
# Environment variables:
#   ICCDEV_TOOLS_DIR   -- path to Build/Tools or build/Tools
#   ICCDEV_TEST_OUTDIR -- output directory for temporary files and logs
###############################################################################

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
TOOLS_DIR="${ICCDEV_TOOLS_DIR:-$REPO_ROOT/Build/Tools}"
OUTDIR="${ICCDEV_TEST_OUTDIR:-/tmp/iccdev-issue-1097-applyprofiles-hbo}"

if [ ! -d "$TOOLS_DIR" ]; then
  for candidate in "$REPO_ROOT/build/Tools" "$REPO_ROOT/Build/Tools"; do
    if [ -d "$candidate" ]; then
      TOOLS_DIR="$candidate"
      break
    fi
  done
fi

APPLY="$TOOLS_DIR/IccApplyProfiles/iccApplyProfiles"
if [ ! -x "$APPLY" ]; then
  echo "[FAIL] missing executable: $APPLY"
  exit 1
fi

BUILD_DIR="$(cd "$TOOLS_DIR/.." && pwd)"
export LD_LIBRARY_PATH="$BUILD_DIR/IccProfLib:$BUILD_DIR/IccXML:$BUILD_DIR/IccConnect:${LD_LIBRARY_PATH:-}"

mkdir -p "$OUTDIR"
ASAN_PROBE="$OUTDIR/issue-1097-asan-probe.txt"
asan_instrumented=0
if command -v ldd >/dev/null 2>&1 &&
   ldd "$APPLY" > "$ASAN_PROBE" 2>/dev/null &&
   grep -q 'libasan' "$ASAN_PROBE"; then
  asan_instrumented=1
elif command -v nm >/dev/null 2>&1 &&
     nm -D "$APPLY" > "$ASAN_PROBE" 2>/dev/null &&
     grep -q '__asan' "$ASAN_PROBE"; then
  asan_instrumented=1
elif command -v strings >/dev/null 2>&1 &&
     strings "$APPLY" > "$ASAN_PROBE" 2>/dev/null &&
     grep -q '__asan' "$ASAN_PROBE"; then
  asan_instrumented=1
fi

if [ "$asan_instrumented" -ne 1 ]; then
  echo "[SKIP] iccApplyProfiles is not ASAN-instrumented"
  exit 77
fi

if ! command -v base64 >/dev/null 2>&1; then
  echo "[FAIL] base64 is required"
  exit 1
fi

if ! command -v sha256sum >/dev/null 2>&1; then
  echo "[FAIL] sha256sum is required"
  exit 1
fi

if ! command -v timeout >/dev/null 2>&1; then
  echo "[FAIL] timeout is required"
  exit 1
fi

TMPDIR="$(mktemp -d "$OUTDIR/issue-1097.XXXXXX")"
trap 'rm -rf "$TMPDIR"' EXIT

SRC_TIF="$TMPDIR/rgb-4x4-8bit.tif"
POC_ICC="$TMPDIR/hbo-CIccCamConverter-JabToXYZ-IccCAM_cpp-Line614.icc"
OUT_TIF="$TMPDIR/out.tif"
LOG="$OUTDIR/issue-1097-applyprofiles-hbo.log"

base64 -d > "$SRC_TIF" <<'EOF_TIF'
SUkqAAgAAAAMAAABAwABAAAABAAAAAEBAwABAAAABAAAAAIBAwADAAAAngAAAAMBAwABAAAAAQAAAAYBAwABAAAAAgAAABEBBAABAAAAtAAAABUBAwABAAAAAwAAABYBAwABAAAABAAAABcBBAABAAAAMAAAABoBBQABAAAApAAAABsBBQABAAAArAAAACgBAwABAAAAAgAAAAAAAAAIAAgACABIAAAAAQAAAEgAAAABAAAAAACAVQCAqgCA/wCAAFWAVVWAqlWA/1WAAKqAVaqAqqqA/6qAAP+AVf+Aqv+A//+A
EOF_TIF

base64 -d > "$POC_ICC" <<'EOF_ICC'
AAAQFAAAAAAFAAAAc3BhY1JHQiBYWVogB+oAAwAEABAANAAFYWNzcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAPbWAAEAAAAA0y1JQ0MgyLVDyViN2FnnpsfuLbV56AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFZGVzYwAAAMAAAAA+QTJCMQAAAQAAAA0wQjJBMQAADjAAAAFYd3RwdAAAD4gAAAAUY3BydAAAD5wAAAB4bWx1YwAAAAAAAAABAAAADGVuVVMAAAAiAAAAHABzAFIARwBCACAAYwBhAGwAYwAgAHQAZQBzAHQAZQByAAAAAG1wZXQAAAAAAAMAAwAAAAEAAAAYAAANGGNhbGMAAAAAAAMAAwAAAAsAAABwAAAJDAAACQwAAACcAAAJqAAAADwAAAnkAAAAfAAACmAAAABUAAAKtAAAACwAAArgAAAALAAACwwAAAAsAAALOAAAADwAAAt0AAAAbAAAC+AAAAD8AAAM3AAAADxmdW5jAAAAAAAAARJkYXRhP4AAAGRhdGE/gAAAZGF0YT+AAAB0cHV0AAAAAnRnZXQAAAACc3VtIAABAABkYXRhQEAAAGVxICAAAAAAdHB1dAADAABkYXRhP4AAAGRhdGE/gAAAZGF0YT+AAABjdXJ2AAD2/3N1bSAAAQAAZGF0YUBAAABlcSAgAAAAAHRwdXQABAAAZGF0YT+AAABkYXRhQAAAAGRhdGFAQAAAbXR4IAABAABkYXRhAAAAAGRhdGE/gAAAZGF0YUAAAABzdWIgAAIAAHN1bSAAAQAAZGF0YQAAAABlcSAgAAAAAHRwdXQABQAAZGF0YT+AAABkYXRhP4AAAGRhdGE/wAAAY2x1dAACAABkYXRhPoAAAGRhdGE/AAAAZGF0YT9AAABzdWIgAAIAAHN1bSAAAQAAZGF0YQAAAABlcSAgAAAAAHRwdXQABgAAZGF0YT+AAABkYXRhQAAAAGRhdGFAQAAAY2FsYwADAABkYXRhQAAAAGRhdGFAQAAAZGF0YUCAAABzdWIgAAIAAHN1bSAAAQAAZGF0YQAAAABlcSAgAAAAAHRwdXQABwAAZGF0YT8AAAB0aW50AAQAAGRhdGE/gAAAZGF0YUBAAABkYXRhQMAAAHN1YiAAAgAAc3VtIAAAAABkYXRhAAAAAGVxICAAAAAAdHB1dAAIAABkYXRhQsgAAGRhdGEAAAAAZGF0YQAAAABmSmFiAAUAAGRhdGE/dtXQZGF0YT+AAABkYXRh//8spXN1YiAAAgAAYWJzIAACAABzdW0gAAEAAGRhdGE6gxJvbGUgIAAAAAB0cHV0AAkAAGRhdGE/dtXQZGF0YT+AAABkYXRhP1MspXRKYWIABgAAZGF0YULIAABkYXRhAAAAAGRhdGEAAAAAc3ViIAACAABhYnMgAAIAAHN1bSAAAQAAZGF0YT3MzM1sZSAgAAAAAHRwdXQACgAAZGF0YUAAAABlbGVtAAQAAGRhdGE/gAAAZGF0YUBAAABkYXRhQMAAAHN1YiAAAgAAc3VtIAABAABkYXRhAAAAAGVxICAAAAAAdHB1dAALAABkYXRhLtvm/2RhdGEu2+b/ZXEgIAAAAAB0cHV0AAwAAGRhdGE/gAAAdHB1dAAVAABkYXRhQAAAAHRwdXQAFgAAZGF0YUAAAABkYXRhQAAAAGRhdGFAAAAAdGdldAAVAABkYXRhP4AAAGFkZCAAAAAAdHB1dAAVAAB0Z2V0ABYAAGRhdGE/gAAAYWRkIAAAAAB0cHV0ABYAAG10eCAABwAAZGF0YUAAAABkYXRhQAAAAGRhdGFAAAAAc3ViIAACAABzdW0gAAEAAGRhdGEAAAAAZXEgIAAAAAB0cHV0AA0AAGRhdGE/gAAAZGF0YUAAAABkYXRhQEAAAHRwdXQAFwACdGdldAAXAAJkYXRhP4AAAGRhdGFAAAAAZGF0YUBAAABzdWIgAAIAAGFicyAAAgAAc3VtIAABAABkYXRhPczMzWx0ICAAAAAAdHB1dAAOAABkYXRhP4AAAGRhdGFAAAAAZGF0YUBAAABjb3B5AAIhAHRwdXQAFwACdGdldAAXAAJzdWIgAAIAAGFicyAAAgAAc3VtIAABAABkYXRhPczMzWx0ICAAAAAAdHB1dAAPAAB0Z2V0ABcAAHRnZXQAGAAAdGdldAAZAABkYXRhP4AAAGRhdGFAAAAAZGF0YUBAAABzdWIgAAIAAGFicyAAAgAYc3VtIAABAABkYXRhPczMzWx0ICAAAAAAdHB1dAAQAABkYXRhQsgAAGRhdGEAAAAAZGF0YQAAAABkYXRhAAAAAGRhdGFCyAAAZGF0YQAAAABkYXRhAAAAAGRhdGEAAAAAZGF0YULIAAB0cHV0ABoACHRnZXQAGgAAdGdldAAeAAB0Z2V0ACIAAGRhdGFCyAAAZGF0YULIAABkYXRhQsgAAHN1YiAAAgAAYWJzIAACAABzdW0gAAEAAGRhdGE9zMzNbHQgIAAAAAB0cHV0ABEAAGRhdGE/AAAAZGF0YT8AAABkYXRhPwAAAGRhdGE/wAAAZGF0YT6AAAB0cHV0ACQAAHRwdXQAIwAAdGdldAAjAABzbXVsAAIAAHRnZXQAJAAAc2FkZAACAABkYXRhP4AAAGRhdGE/gAAAZGF0YT+AAABzdWIgAAIAAGFicyAAAgAAc3VtIAABAABkYXRhPczMzWx0ICAAAAAAdHB1dAASAABkYXRhPwAAAGRhdGE/AAAAZGF0YT8AAABkYXRhP8AAAGRhdGE+gAAAZGF0YQAAAABkYXRhP2ZmZnRwdXQAIwABdHB1dAAmAAB0cHV0ACUAAHRnZXQAJQAAc211bAACAAB0Z2V0ACYAAHNhZGQAAgAAdGdldAAjAABjb3B5AAAAAXZtYXgGAgAAdGdldAAkAABjb3B5AAAAAXZtaW4AAgAAZGF0YT9mZmZkYXRhP2ZmZmRhdGE/ZmZmc3ViIAACAABhYnMgAAIAAHN1bSAAAQAAZGF0YT3MzM1sdCAgAAAAAHRwdXQAEwAAZGF0YQAAAABkYXRhP4AAAGRhdGFAAAAAZGF0YUBAAABkYXRhQIAAAGRhdGFAoAAAZGF0YUDAAABjYWxjAAgAAGRhdGFAoAAAZGF0YUDAAABkYXRhAAAAAGRhdGE/gAAAZGF0YUAAAABkYXRhQIAAAHN1YiAAAAAAYWJzIAAFAABzdW0gAAQAAGRhdGE9zMzNbHQgIAAAAAB0cHV0ABQAAHRnZXQAAAAUc3VtIAATAABkYXRhQagAAGVxICAAAAAAaWYgIAAAAAhlbHNlAAAABGVudiABAgMEaWYgIAAAAAFlbHNlAAAAA2NvcHkAAAABaW4gIAAAAAJjdXJ2AAkAAG10eCAACgAAb3V0IAAAAAJkYXRhAAAAAGRhdGEAAAAAZGF0YQAAAABvdXQgAAAAAmN2c3QAAAAAAAMAAwAAACQAAAAoAAAATAAAACgAAAB0AAAAKGN1cmYAAAAAAAEAAHBhcmYAAAAAAAAAAD+AAAA/AAAAAAAAAAAAAABjdXJmAAAAAAABAABwYXJmAAAAAAAAAAA/gAAAP4AAAAAAAAAAAAAAY3VyZgAAAAAAAQAAcGFyZgAAAAAAAAAAP4AAAD/AAAAAAAAAAAAAAG1hdGYAAAAAAAMAAz+AAAA/gAAAv4AAAEAAAAA/gAAAv4AAAD+AAAC/gAYAP4AAAAAAAAAAAAAAAAAAAGNsdXQAAAAAAAMAAwICAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD9AAAAAAAAAPwAAAAAAAAAAAAAAPwAAAD9AAAA+gAAAAAAAAAAAAAA+gAAAAAAAAD9AAAA+gAAAPwAAAAAAAAA+gAAAPwAAAD9AAABjYWxjAAAAAAADAAMAAAAAAAAAGAAAADxmdW5jAAAAAAAAAAZpbiAgAAAAAmRhdGE/gAAAZGF0YT+AAABkYXRhP4AAAGFkZCAAAgAAb3V0IAAAAAJ0aW50AAAAAAABAANmbDMyAAAAAAAAAABAAAAAQIAAAEAAAABAgAAAQQAAAEp0b1gAAAAAAAAAAAAABIM/gAAAP1MspUP6MD9BAAAAAKAAAIA/P6PXgAAAWHRvSgAAAAAAAwADP3bV0D+AAAA/UyylQ/oAAEGgAAA/MKPXP4AAAKSAAABtYXRmAAAAAAADAAM/gAAAAAAAAAAAAAAAAAAAP4AAAAAAAAAAAAAAAAAAAD+AAAAAAAAAAAAAAAAAAABjYWxjAAAAAAAHAAYAAAAAAAAAGAAAAFRmdW5jAAAAAAAAAAlpbiAgAAAAAG91dCAAAgAAaW4gIAAFAAFvdXQgAAAAAWluICAAAQAAaW4gIAACAABvdXQgAAMAAWluICAABAAAb3V0IAAFAABjdnN0AAAAAAADAAMAAAAkAAAASAAAAGwAAABIAAAAtAAAAEhjdXJmAAAAAAACAAA9Ja7mcGFyZgAAAAAAAAAAP4AAAD2ciFQ8TMzNAAAAAHBhcmYAAAAAAAAAAEAZmZo/cWK2PVRrWTxMzM1jdXJmAAAAAAACAAA9Ja7mcGFyZgAAAAAAAAAAP4AAAD2ciFQ8TMwqAAAAAHBhcmYAAAAAAAAAAEAZmZo/cWK2PVRrWTxMzM1jdXJmAAAAAAACAAA9Ja7mcGFyZgAAAAAAAAAAP4AAAD2ciFQ8TMzNAAAAAHBhcmYAAAAAAAAAAEAZmZo/cWK2PVRrWTxMzM1tYXRmAAAAAAADAAM+7peNPsUr1D5giM4AAAAcAGMAYQBsAGMAVQBuAGQAZQByAFMAdABhAGMAawBfAGEAdABhAG4AAG1wZXQAAAAAAAMAAwAAAAEAAAAYAAADxGNhbGMAAAFlbHNlAAAAA3RwdXQAAAAAcG9wIAAAAABkYXRhREgAAHRwdXQAAAAAZW52IE1uTG1pZiAgAAAAAWVsc2UAcGFyZgAAAGRhdGFAwAAAc3ViIAACAABzdW0gAAEACGRhdGEAAAAAZXEgIAAAAAB0cHV0AAgAAGRhdGFCyAAAZGF0YQAAAABkYXRhAAAAAGZKYWIABQAAZGF0YT921dBkYXRhP4AAAGRhdGE/Uyylc3ViICEAAgAAYWJzIAACAABzdW0gAAEAAGRhdGE6gxJvbGUgIAAAAAB0cHV0AAkAAGRhdGE/dtXQZGF0YT+AAABkYXRhP1MspXRKYWIABgAAZGF0YULIAABkYXRhAAAAAGRhdGEAAAAAc3ViIAACAABhYnMgAAIAAHN1bSAAAP8AZGF0YT3MzM1sZSAgAAAAAHRwdXQACgAAZGF0YT8AAABlbGVtAAQAAGRhdGE/gAAAZGF0YUBAAABkYXRhQMAAAHN1YiAAAgAAc3VtIAABAABkYXRhAAAAAGVxICAAAAAAdHB1dAALAABkYXRhLtvmQAAAZGF0YUCAAABkYXRhQKAAAGRhdGFAwAAAY2FsYwAIAABkYXRhQKAAAGRhdGFAwAAAZGF0YQAAAABkYXRhP4AAAGRhdGFAAAAAZGF0YUCAAABzdWIgAAAAAGFicyAABQAAc3Vt
EOF_ICC

expected_tif="edfa74c09e5b2822bf9c8ba1c7d25d801400066207e762ab2ab97fafec417073"
expected_icc="ebab7c86d182fd52637cf936f931018aedda2ba3fa371f924fbb7f96fe311fca"
actual_tif="$(sha256sum "$SRC_TIF" | awk '{print $1}')"
actual_icc="$(sha256sum "$POC_ICC" | awk '{print $1}')"

if [ "$actual_tif" != "$expected_tif" ]; then
  echo "[FAIL] TIFF fixture digest mismatch: $actual_tif"
  exit 1
fi

if [ "$actual_icc" != "$expected_icc" ]; then
  echo "[FAIL] ICC fixture digest mismatch: $actual_icc"
  exit 1
fi

if [ -z "${ASAN_OPTIONS:-}" ]; then
  export ASAN_OPTIONS="print_scariness=1:halt_on_error=0:detect_leaks=0"
else
  case ":$ASAN_OPTIONS:" in
    *:print_scariness=*) ;;
    *) export ASAN_OPTIONS="print_scariness=1:$ASAN_OPTIONS" ;;
  esac
  case ":$ASAN_OPTIONS:" in
    *:detect_leaks=*) ;;
    *) export ASAN_OPTIONS="$ASAN_OPTIONS:detect_leaks=0" ;;
  esac
fi
export UBSAN_OPTIONS="${UBSAN_OPTIONS:-halt_on_error=0:print_stacktrace=1}"

set +e
timeout 30 "$APPLY" -threads 1 "$SRC_TIF" "$OUT_TIF" 0 0 0 0 1 "$POC_ICC" 10000 > "$LOG" 2>&1
exit_code=$?
set -e

if grep -qE 'ERROR: AddressSanitizer|SUMMARY: AddressSanitizer|UndefinedBehaviorSanitizer|runtime error:|LeakSanitizer|MemorySanitizer' "$LOG"; then
  echo "[FAIL] sanitizer finding while replaying issue 1097 iccApplyProfiles PoC"
  sed -n '1,120p' "$LOG"
  exit 1
fi

if [ "$exit_code" -eq 124 ]; then
  echo "[FAIL] iccApplyProfiles timed out"
  sed -n '1,80p' "$LOG"
  exit 1
fi

if [ "$exit_code" -ge 128 ] && [ "$exit_code" -le 192 ]; then
  echo "[FAIL] iccApplyProfiles crashed with signal $((exit_code - 128))"
  sed -n '1,80p' "$LOG"
  exit 1
fi

echo "[PASS] issue 1097 iccApplyProfiles CAM sub-element PoC completed without sanitizer findings"
exit 0
