#!/bin/bash
###############################################################################
# iccDEV v5 NamedCMM profile regression tests
###############################################################################
#
# Exercises v5 non-spectral profile paths that are used by iccApplyNamedCmm and
# iccRoundTrip.  The fixtures are embedded as base64 so the regression remains
# self-contained and avoids adding binary profile artifacts to the repository.
#
# Environment variables:
#   ICCDEV_TOOLS_DIR   -- path to Build/Tools or build/Tools
#   ICCDEV_TEST_OUTDIR -- output directory for temporary files and logs
###############################################################################

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
TOOLS_DIR="${ICCDEV_TOOLS_DIR:-$REPO_ROOT/Build/Tools}"
OUTDIR="${ICCDEV_TEST_OUTDIR:-/tmp/iccdev-v5-namedcmm-regressions}"
BUILD_ROOT="$(cd "$TOOLS_DIR/.." 2>/dev/null && pwd -P)"

export LD_LIBRARY_PATH="$BUILD_ROOT/IccProfLib:$BUILD_ROOT/IccXML:$BUILD_ROOT/IccJSON${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
export ASAN_OPTIONS="${ASAN_OPTIONS:-halt_on_error=1,detect_leaks=0}"
export UBSAN_OPTIONS="${UBSAN_OPTIONS:-halt_on_error=1,print_stacktrace=1}"

APPLYNCM="$TOOLS_DIR/IccApplyNamedCmm/iccApplyNamedCmm"
ROUNDTRIP="$TOOLS_DIR/IccRoundTrip/iccRoundTrip"
DATA_FILE="$REPO_ROOT/.github/ci/test-data/test-data-rgb-8bit.txt"

PASS=0
FAIL=0
TOTAL=0

mkdir -p "$OUTDIR/profiles"

decode_profile() {
  local name="$1"
  local data="$2"

  printf '%s' "$data" | base64 -d > "$OUTDIR/profiles/$name"
}

run_case() {
  local test_id="$1"
  local description="$2"
  shift 2

  TOTAL=$((TOTAL + 1))
  local logfile="$OUTDIR/${test_id}.log"
  local exit_code=0

  timeout 60 "$@" > "$logfile" 2>&1 || exit_code=$?

  if grep -q "ERROR: AddressSanitizer\\|runtime error:" "$logfile" 2>/dev/null; then
    echo "  [FAIL] $description - sanitizer finding"
    sed -n '1,80p' "$logfile"
    FAIL=$((FAIL + 1))
  elif [ "$exit_code" -ne 0 ]; then
    echo "  [FAIL] $description - exit $exit_code"
    sed -n '1,80p' "$logfile"
    FAIL=$((FAIL + 1))
  else
    echo "  [PASS] $description"
    PASS=$((PASS + 1))
  fi
}

echo "=== v5 NamedCMM profile regressions ==="

if [ ! -x "$APPLYNCM" ]; then
  echo "  [FAIL] missing executable: $APPLYNCM"
  exit 1
fi

if [ ! -x "$ROUNDTRIP" ]; then
  echo "  [FAIL] missing executable: $ROUNDTRIP"
  exit 1
fi

if [ ! -f "$DATA_FILE" ]; then
  echo "  [FAIL] missing RGB data file: $DATA_FILE"
  exit 1
fi

decode_profile "dtob-btod-all-intents.icc" "AAAKJAAAAAAFAAAAbW50clJHQiBYWVogB+gAAQABAAAAAAAAYWNzcEFQUEwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPbVAAEAAAAA0yx0ZXN0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARZGVzYwAAAVAAAABIY3BydAAAAZgAAABMd3RwdAAAAeQAAAAUclhZWgAAAfgAAAAUZ1hZWgAAAgwAAAAUYlhZWgAAAiAAAAAUclRSQwAAAjQAAAAQZ1RSQwAAAkQAAAAQYlRSQwAAAlQAAAAQRDJCMAAAAmQAAAD4QjJEMAAAA1wAAAD4RDJCMQAABFQAAAD4QjJEMQAABUwAAAD4RDJCMgAABkQAAAD4QjJEMgAABzwAAAD4RDJCMwAACDQAAAD4QjJEMwAACSwAAAD4bWx1YwAAAAAAAAABAAAADGVuVVMAAAAqAAAAHABBAGwAbAAgAEQAVABvAEIAKwBCAFQAbwBEACAASQBuAHQAZQBuAHQAcwAAbWx1YwAAAAAAAAABAAAADGVuVVMAAAAuAAAAHABDAG8AcAB5AHIAaQBnAGgAdAAgADIAMAAyADYAIABJAEMAQwAgAFQAZQBzAHQAAFhZWiAAAAAAAAD21QABAAAAANMsWFlaIAAAAAAAAGmTAAA2bAAABPBYWVogAAAAAAAAW4sAALcXAAAeg1hZWiAAAAAAAAAuNQAAEnsAAPNTY3VydgAAAAAAAAABAjMAAGN1cnYAAAAAAAAAAQIzAABjdXJ2AAAAAAAAAAECMwAAbXBldAAAAAAAAwADAAAAAgAAACAAAACcAAAAvAAAADxjdnN0AAAAAAADAAMAAAAkAAAAKAAAAEwAAAAoAAAAdAAAAChjdXJmAAAAAAABAABwYXJmAAAAAAAAAAA/gAAAP4AAAAAAAAAAAAAAY3VyZgAAAAAAAQAAcGFyZgAAAAAAAAAAP4AAAD+AAAAAAAAAAAAAAGN1cmYAAAAAAAEAAHBhcmYAAAAAAAAAAD+AAAA/gAAAAAAAAAAAAABtYXRmAAAAAAADAAM/gAAAAAAAAAAAAAAAAAAAP4AAAAAAAAAAAAAAAAAAAD+AAAAAAAAAAAAAAAAAAABtcGV0AAAAAAADAAMAAAACAAAAIAAAADwAAABcAAAAnG1hdGYAAAAAAAMAAz+AAAAAAAAAAAAAAAAAAAA/gAAAAAAAAAAAAAAAAAAAP4AAAAAAAAAAAAAAAAAAAGN2c3QAAAAAAAMAAwAAACQAAAAoAAAATAAAACgAAAB0AAAAKGN1cmYAAAAAAAEAAHBhcmYAAAAAAAAAAD+AAAA/gAAAAAAAAAAAAABjdXJmAAAAAAABAABwYXJmAAAAAAAAAAA/gAAAP4AAAAAAAAAAAAAAY3VyZgAAAAAAAQAAcGFyZgAAAAAAAAAAP4AAAD+AAAAAAAAAAAAAAG1wZXQAAAAAAAMAAwAAAAIAAAAgAAAAnAAAALwAAAA8Y3ZzdAAAAAAAAwADAAAAJAAAACgAAABMAAAAKAAAAHQAAAAoY3VyZgAAAAAAAQAAcGFyZgAAAAAAAAAAP4AAAD+AAAAAAAAAAAAAAGN1cmYAAAAAAAEAAHBhcmYAAAAAAAAAAD+AAAA/gAAAAAAAAAAAAABjdXJmAAAAAAABAABwYXJmAAAAAAAAAAA/gAAAP4AAAAAAAAAAAAAAbWF0ZgAAAAAAAwADP4AAAAAAAAAAAAAAAAAAAD+AAAAAAAAAAAAAAAAAAAA/gAAAAAAAAAAAAAAAAAAAbXBldAAAAAAAAwADAAAAAgAAACAAAAA8AAAAXAAAAJxtYXRmAAAAAAADAAM/gAAAAAAAAAAAAAAAAAAAP4AAAAAAAAAAAAAAAAAAAD+AAAAAAAAAAAAAAAAAAABjdnN0AAAAAAADAAMAAAAkAAAAKAAAAEwAAAAoAAAAdAAAAChjdXJmAAAAAAABAABwYXJmAAAAAAAAAAA/gAAAP4AAAAAAAAAAAAAAY3VyZgAAAAAAAQAAcGFyZgAAAAAAAAAAP4AAAD+AAAAAAAAAAAAAAGN1cmYAAAAAAAEAAHBhcmYAAAAAAAAAAD+AAAA/gAAAAAAAAAAAAABtcGV0AAAAAAADAAMAAAACAAAAIAAAAJwAAAC8AAAAPGN2c3QAAAAAAAMAAwAAACQAAAAoAAAATAAAACgAAAB0AAAAKGN1cmYAAAAAAAEAAHBhcmYAAAAAAAAAAD+AAAA/gAAAAAAAAAAAAABjdXJmAAAAAAABAABwYXJmAAAAAAAAAAA/gAAAP4AAAAAAAAAAAAAAY3VyZgAAAAAAAQAAcGFyZgAAAAAAAAAAP4AAAD+AAAAAAAAAAAAAAG1hdGYAAAAAAAMAAz+AAAAAAAAAAAAAAAAAAAA/gAAAAAAAAAAAAAAAAAAAP4AAAAAAAAAAAAAAAAAAAG1wZXQAAAAAAAMAAwAAAAIAAAAgAAAAPAAAAFwAAACcbWF0ZgAAAAAAAwADP4AAAAAAAAAAAAAAAAAAAD+AAAAAAAAAAAAAAAAAAAA/gAAAAAAAAAAAAAAAAAAAY3ZzdAAAAAAAAwADAAAAJAAAACgAAABMAAAAKAAAAHQAAAAoY3VyZgAAAAAAAQAAcGFyZgAAAAAAAAAAP4AAAD+AAAAAAAAAAAAAAGN1cmYAAAAAAAEAAHBhcmYAAAAAAAAAAD+AAAA/gAAAAAAAAAAAAABjdXJmAAAAAAABAABwYXJmAAAAAAAAAAA/gAAAP4AAAAAAAAAAAAAAbXBldAAAAAAAAwADAAAAAgAAACAAAACcAAAAvAAAADxjdnN0AAAAAAADAAMAAAAkAAAAKAAAAEwAAAAoAAAAdAAAAChjdXJmAAAAAAABAABwYXJmAAAAAAAAAAA/gAAAP4AAAAAAAAAAAAAAY3VyZgAAAAAAAQAAcGFyZgAAAAAAAAAAP4AAAD+AAAAAAAAAAAAAAGN1cmYAAAAAAAEAAHBhcmYAAAAAAAAAAD+AAAA/gAAAAAAAAAAAAABtYXRmAAAAAAADAAM/gAAAAAAAAAAAAAAAAAAAP4AAAAAAAAAAAAAAAAAAAD+AAAAAAAAAAAAAAAAAAABtcGV0AAAAAAADAAMAAAACAAAAIAAAADwAAABcAAAAnG1hdGYAAAAAAAMAAz+AAAAAAAAAAAAAAAAAAAA/gAAAAAAAAAAAAAAAAAAAP4AAAAAAAAAAAAAAAAAAAGN2c3QAAAAAAAMAAwAAACQAAAAoAAAATAAAACgAAAB0AAAAKGN1cmYAAAAAAAEAAHBhcmYAAAAAAAAAAD+AAAA/gAAAAAAAAAAAAABjdXJmAAAAAAABAABwYXJmAAAAAAAAAAA/gAAAP4AAAAAAAAAAAAAAY3VyZgAAAAAAAQAAcGFyZgAAAAAAAAAAP4AAAD+AAAAAAAAAAAAAAA=="
decode_profile "dtob-brdf.icc" "AAADAAAAAAAFAAAAbW50clJHQiBYWVogB+gAAQABAAAAAAAAYWNzcEFQUEwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPbVAAEAAAAA0yx0ZXN0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKZGVzYwAAAPwAAABAY3BydAAAATwAAABMd3RwdAAAAYgAAAAUclhZWgAAAZwAAAAUZ1hZWgAAAbAAAAAUYlhZWgAAAcQAAAAUclRSQwAAAdgAAAAQZ1RSQwAAAegAAAAQYlRSQwAAAfgAAAAQYkRCMAAAAggAAAD4bWx1YwAAAAAAAAABAAAADGVuVVMAAAAkAAAAHABCAFIARABGACAARABUAG8AQgAwACAAUAByAG8AZgBpAGwAZW1sdWMAAAAAAAAAAQAAAAxlblVTAAAALgAAABwAQwBvAHAAeQByAGkAZwBoAHQAIAAyADAAMgA2ACAASQBDAEMAIABUAGUAcwB0AABYWVogAAAAAAAA9tUAAQAAAADTLFhZWiAAAAAAAABpkwAANmwAAATwWFlaIAAAAAAAAFuLAAC3FwAAHoNYWVogAAAAAAAALjUAABJ7AADzU2N1cnYAAAAAAAAAAQIzAABjdXJ2AAAAAAAAAAECMwAAY3VydgAAAAAAAAABAjMAAG1wZXQAAAAAAAMAAwAAAAIAAAAgAAAAnAAAALwAAAA8Y3ZzdAAAAAAAAwADAAAAJAAAACgAAABMAAAAKAAAAHQAAAAoY3VyZgAAAAAAAQAAcGFyZgAAAAAAAAAAP4AAAD+AAAAAAAAAAAAAAGN1cmYAAAAAAAEAAHBhcmYAAAAAAAAAAD+AAAA/gAAAAAAAAAAAAABjdXJmAAAAAAABAABwYXJmAAAAAAAAAAA/gAAAP4AAAAAAAAAAAAAAbWF0ZgAAAAAAAwADP4AAAAAAAAAAAAAAAAAAAD+AAAAAAAAAAAAAAAAAAAA/gAAAAAAAAAAAAAAAAAAA"
decode_profile "btod-all-intents-no-dtob.icc" "AAAFDAAAAAAFAAAAbW50clJHQiBYWVogB+gAAQABAAAAAAAAYWNzcEFQUEwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPbVAAEAAAAA0yx0ZXN0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANZGVzYwAAASAAAABQY3BydAAAAXAAAABMd3RwdAAAAbwAAAAUclhZWgAAAdAAAAAUZ1hZWgAAAeQAAAAUYlhZWgAAAfgAAAAUclRSQwAAAgwAAAAQZ1RSQwAAAhwAAAAQYlRSQwAAAiwAAAAQQjJEMAAAAjwAAAC0QjJEMQAAAvAAAAC0QjJEMgAAA6QAAAC0QjJEMwAABFgAAAC0bWx1YwAAAAAAAAABAAAADGVuVVMAAAA0AAAAHABCAFQAbwBEACAAQQBsAGwAIABJAG4AdABlAG4AdABzACAAKABuAG8AIABEAFQAbwBCACltbHVjAAAAAAAAAAEAAAAMZW5VUwAAAC4AAAAcAEMAbwBwAHkAcgBpAGcAaAB0ACAAMgAwADIANgAgAEkAQwBDACAAVABlAHMAdAAAWFlaIAAAAAAAAPbVAAEAAAAA0yxYWVogAAAAAAAAaZMAADZsAAAE8FhZWiAAAAAAAABbiwAAtxcAAB6DWFlaIAAAAAAAAC41AAASewAA81NjdXJ2AAAAAAAAAAECMwAAY3VydgAAAAAAAAABAjMAAGN1cnYAAAAAAAAAAQIzAABtcGV0AAAAAAADAAMAAAABAAAAGAAAAJxjdnN0AAAAAAADAAMAAAAkAAAAKAAAAEwAAAAoAAAAdAAAAChjdXJmAAAAAAABAABwYXJmAAAAAAAAAAA/gAAAP4AAAAAAAAAAAAAAY3VyZgAAAAAAAQAAcGFyZgAAAAAAAAAAP4AAAD+AAAAAAAAAAAAAAGN1cmYAAAAAAAEAAHBhcmYAAAAAAAAAAD+AAAA/gAAAAAAAAAAAAABtcGV0AAAAAAADAAMAAAABAAAAGAAAAJxjdnN0AAAAAAADAAMAAAAkAAAAKAAAAEwAAAAoAAAAdAAAAChjdXJmAAAAAAABAABwYXJmAAAAAAAAAAA/gAAAP4AAAAAAAAAAAAAAY3VyZgAAAAAAAQAAcGFyZgAAAAAAAAAAP4AAAD+AAAAAAAAAAAAAAGN1cmYAAAAAAAEAAHBhcmYAAAAAAAAAAD+AAAA/gAAAAAAAAAAAAABtcGV0AAAAAAADAAMAAAABAAAAGAAAAJxjdnN0AAAAAAADAAMAAAAkAAAAKAAAAEwAAAAoAAAAdAAAAChjdXJmAAAAAAABAABwYXJmAAAAAAAAAAA/gAAAP4AAAAAAAAAAAAAAY3VyZgAAAAAAAQAAcGFyZgAAAAAAAAAAP4AAAD+AAAAAAAAAAAAAAGN1cmYAAAAAAAEAAHBhcmYAAAAAAAAAAD+AAAA/gAAAAAAAAAAAAABtcGV0AAAAAAADAAMAAAABAAAAGAAAAJxjdnN0AAAAAAADAAMAAAAkAAAAKAAAAEwAAAAoAAAAdAAAAChjdXJmAAAAAAABAABwYXJmAAAAAAAAAAA/gAAAP4AAAAAAAAAAAAAAY3VyZgAAAAAAAQAAcGFyZgAAAAAAAAAAP4AAAD+AAAAAAAAAAAAAAGN1cmYAAAAAAAEAAHBhcmYAAAAAAAAAAD+AAAA/gAAAAAAAAAAAAAA="

DTOB_PROFILE="$OUTDIR/profiles/dtob-btod-all-intents.icc"
BRDF_PROFILE="$OUTDIR/profiles/dtob-brdf.icc"
BTOD_ONLY_PROFILE="$OUTDIR/profiles/btod-all-intents-no-dtob.icc"

run_case "v5-dtob-apply" "iccApplyNamedCmm accepts v5 non-spectral DToB tags" \
  "$APPLYNCM" "$DATA_FILE" "0:9:12" 0 "$DTOB_PROFILE" 1

run_case "v5-btod-only-fallback" "iccApplyNamedCmm falls back to v5 matrix/TRC without DToB" \
  "$APPLYNCM" "$DATA_FILE" "0:9:12" 0 "$BTOD_ONLY_PROFILE" 1

run_case "v5-brdf-direct-60" "iccApplyNamedCmm accepts v5 BRDF direct intent 60" \
  "$APPLYNCM" "$DATA_FILE" "0:9:12" 0 "$BRDF_PROFILE" 60

run_case "v5-brdf-direct-61" "iccApplyNamedCmm accepts v5 BRDF direct intent 61" \
  "$APPLYNCM" "$DATA_FILE" "0:9:12" 0 "$BRDF_PROFILE" 61

run_case "v5-roundtrip-mpe" "iccRoundTrip use_mpe selects v5 DToB/BToD tags" \
  "$ROUNDTRIP" "$DTOB_PROFILE" 1 1

echo "v5 NamedCMM regressions: $PASS passed, $FAIL failed, $TOTAL total"

if [ "$FAIL" -ne 0 ]; then
  exit 1
fi

exit 0
